gatsby-inc/gatsby-interface

__tests__/Toast.js
__tests__/__snapshots__/Toast.js.snap
package.json
src/components/Toast/MessageWithLink.js
src/components/Toast/README.md
src/components/Toast/Toast.js
src/components/Toast/Toast.stories.js
src/components/Toast/ToastContext.js
src/components/Toast/constants.js
src/components/Toast/hooks.js
src/components/Toast/index.js
src/index.js
yarn.lock

This is a port of `Toast` component from cloud; the goal was to keep the styles and see if it can be improved. Main changes when compared to the cloud version:
1. The toast itself now can support different types. As an example, I've added an `error` type — it will not disappear on timeout and has `"assertive"` type that makes screen readers read the message immediately (which is the desired behaviour for an "error" alert).
2. `Toast` does not use `dangerouslySetInnerHTML` to display its message anymore. Judging by its use in cloud, seems like its purpose was to render text containing `<strong>`  tags. The same can be achieved with this new component like this: 
```javascript
showSuccessToast(
<React.Fragment>
<strong>User settings</strong> updated sucessfully.
</React.Fragment<
);
``` 
3. …

feat: toast component and hooks

---

src/components/Radio/Radio.js
src/components/Radio/Radio.stories.js

Seems like labels for `emphasized` radios had a larger padding applied. I guess it was meant as an additional indication for a selected option, but it also causes the "jumpiness" in the radio group.

Prevent radio labels from causing other options to jump

---

src/components/Radio/Radio.Skeleton.js
src/components/Radio/Radio.js
src/components/Radio/Radio.stories.js

1. Allow to pass React nodes in `label` prop to `Radio`. This will allow to implement complex labels without drawbacks of forced `dangerouslySetInnerHTML`. It is also still possible to use `dangerouslySetInnerHTML` to render user-generated labels if needed as seen in new stories.
1. Fix an issue that occurs when the radio label is higher than the input itself. Previously, it would make the input unclickable since it had fixed height. Now the input fills all available height, making it impossible to miss it when clicking :)

Accept React nodes as label for Radio component

---

src/components/Radio/Radio.Skeleton.js
src/components/Radio/Radio.js

Now it will be possible to pass `ref` to `Radio` or `RadioSkeleton` allowing for more control over the input.
Most of the changes here are by prettier :)

Forward Radio and RadioSkeleton refs to radio input

---

src/components/core/IntegrationRow/IntegrationRow.js
src/components/core/IntegrationRow/IntegrationRow.stories.js

This allows the user to specify a variant for the integration row content details component
Currently, it only supports details as a row but this allows it to be a column as well. This is for the new designs for cms integrations

Add an alternative variant to integration row content details

---

src/components/core/IntegrationRow/IntegrationRow.js

Links in `IntegrationRow` should open in a new tab. Quick fix to make it so!
Relates to #4865 in `mansion`

Open IntegrationRow links in a new tab

---

.storybook/config.js
__mocks__/styleMock.js
__tests__/__snapshots__/Storyshots.test.js.snap
__tests__/__snapshots__/icons.test.js.snap
jest.config.js
src/components/Radio/Radio.stories.js
src/components/icons/icons.stories.js

This PR fixes several issues that caused Storyshots tests to fail:
* We were importing fonts that are not part of this repo which by default broke Storybook; now `require` is used instead of `import` which allows us Storybook to keep running. In the future we could perhaps add an env variable `STORYBOOK_FONTS_PATH`?
* `storybook-readme` is importing its styles using `import A from "./prismCodeThemes/a11y-dark.css"` yet the actual file was `./prismCodeThemes/a11y-dark.css.js`. This resulted in our `moduleNameMapper ` setup not working properly. I've added another rule to that config to handle this case
* Two minor issues with icon stories would still allow Storybook to run but crashed storyshots tests. Fixed them as well.

chore: fix Storyshots tests

---

package.json

Fixes #75; note that I've only added `dist` folder since files like `package.json`, `README.md`, `CHANGELOG.md` etc [are always included](https://docs.npmjs.com/files/package.json#files) in the package.

chore: add "files" configuration to package.json

---

README.md

Storybook requires a few fonts to run, but they're `.gitignore`d, since they're licensed. I uploaded those fonts to our (private) Google Drive, and added a blurb to the README about where to find them.

Add font info to README

---

src/components/CopyButton/CopyButton.tsx
src/utils/helpers/copyToClipboard.ts

Based on [this great suggestion](https://github.com/gatsby-inc/gatsby-interface/pull/80#pullrequestreview-305508964) from @joshwcomeau, replace `async/await` in `CopyButton` with promises. 
I've also extracted "copy" fallback functionality to its own function in `copyToClipboard` to make the main function cleaner.

fix: replace async/await with promises for CopyButton

---

src/components/Portal/Portal.stories.tsx
src/components/Portal/README.md
src/components/Portal/index.ts

A component that allows to render components outside its parent hierarchy.
This goes directly under the discussion people had yesterday concerning creating opinionated accessible components and is necessary to create the declarative Modal component(s).
```jsx
const App = () => (
<Portal>
<div>Move me somewhere!</di>
</Portal>
)
```
---
A note: It seems that Reachui had some difficulties to be displayed on the DevTools because of the two different `document` used by a React app and React Devtools. Since I was able to display my Portals and there content in my Devtools, I didn't manage this behaviour.
However, I think it could be good to keep it there in case somebody gets in trouble so that we have a workaround solution on this: https://github.com/reach/reach-ui/pull/137

Adding Portal

---

src/components/Modal/Modal.tsx

Fixing the props passed to the modal and to the DialogContent / DialogOverlay.
The idea of this pr is to exclusively passing what DialogOverlay needs as props and to spread the rest to the DialogContent so that DialogContent can have an aria-describedby attribute.
This will be useful when building something like a ConfirmationModal

Fix modal props passing

---

src/components/Modal/Modal.tsx

Just adding some z-index because the tab title "Organization" in gatsbyjs.com was showing over the modal content 😅

Adding z-index on modal

---

src/components/core/SettingsBlock/SettingsBlock.js
src/components/core/SettingsBlock/SettingsBlock.stories.js

Related to this mansion https://github.com/gatsby-inc/mansion/issues/5565 .
Looks like we're passing a `to` prop to a `Button` instead of a link so that we can't naviguate between pages 😅

Fixing link instead of button in setting blocks

---

__tests__/Button.js
__tests__/Storyshots.test.js
__tests__/Toast.js
__tests__/__snapshots__/Button.js.snap
__tests__/__snapshots__/Storyshots.test.js.snap
__tests__/icons.test.js
jest.config.js
package.json
setup-test-env.js
src/components/CopyButton/__tests__/CopyButton.test.tsx
src/components/CopyButton/__tests__/__snapshots__/CopyButton.test.tsx.snap
yarn.lock

This PR should cover the "fixing" part of #116. It fixes as couple of issues happening during `yarn test`:
* `@reach/portal` used under the hood of our modals was breaking snapshot tests, probably due to  those running on `react-test-renderer` and not having access to refs. Using `render` from `@testing-library/react` as `renderer` option for storyshots addon  helped with this problem.
* Side effect of importing `@reach/dialog/styles.css` wasn't handled by Jest config correctly, I've added this file to `moduleNameMapper` configuration.
* I had to omit stories for Decorative dots from snapshot testing since they are impure and get rendered in a different way each time, which ruins the purpose of snapshots.
I've also updated `react-testing-library` to the latest `@testing-library/react` …

chore: fix snapshot testing

---

.babelrc
package.json
yarn.lock

Should implement #119.
Here are some snippets from the `dist/index.es.js` file generated by `yarn build:rollup` command:
```javascript
Modal.propTypes = {
type: PropTypes.oneOf(["success", "info", "warn", "error"])
};
```
```javascript
Button.propTypes = {
size: PropTypes.oneOf(["XL", "L", "M", "S"]),
tone: PropTypes.oneOf(["BRAND", "SUCCESS", "DANGER", "NEUTRAL"]),
variant: PropTypes.oneOf(["PRIMARY", "SECONDARY", "GHOST"]),
leftIcon: PropTypes.node,
rightIcon: PropTypes.node
};
```
It doesn't seem to work with all TS components: looks like it can't handle `React.forwardRef`.

chore: auto-generate propTypes based on TypeScript types

---

__tests__/Storyshots.test.js
__tests__/__snapshots__/Storyshots.test.js.snap
src/components/DecorativeDots/DecorativeDots.tsx
src/utils/helpers/testSafeRandomness.ts

in #118, @Elanhant had to disable the storyshot generated tests for my DecorativeDots component, since their inherent randomness caused problems.
[As discussed](https://github.com/gatsby-inc/gatsby-interface/pull/118#discussion_r347988080), this fix allows those components to be tested by removing that impurity while `process.env.NODE_ENV` was `test`. This way we can still test their general structure in a repeatable, predictable way.

chore: use 'pure' random values in tests

---

__tests__/__snapshots__/Storyshots.test.js.snap
src/components/SidebarNav/SidebarNav.js

This PR aims to create some spacing between the sidenav elements. In fact, when we have elements on more than one line, it's a bit disturbing and it looks like they are two different items.
This PR addresses: https://github.com/gatsby-inc/mansion/issues/5707
The result:

Adjusting sidenav style

---

__tests__/__snapshots__/Storyshots.test.js.snap
src/components/Radio/Radio.js
src/components/Radio/Radio.stories.js

Radio buttons have an "emphasized" style, which features a rainbow gradient:
At some point recently, a bug was introduced which caused the contents of the radio button to appear invisible. This is because the radio button uses pseudoelements to create the gradient effect; the `before` element creates a solid gradient backdrop, and the `after` element adds a white backdrop in front of it, cutting in by a few pixels to show the gradient just around the edges, as a border.
The problem is that both of these layers were sitting _in front_ of the primary content, so the white backdrop was blocking the visibility.
This is a quick-fix. There are better solutions (an SVG mask comes to mind, or possibly adding an inner wrapper to the children to not need potentially-problematic negative z-indices), …

Fix blank radio issue

---

.circleci/config.yml

This should allow CircleCI to run a job to release a new version of gatsby-interface on each push to `master`.

chore: setup release automation

---

src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/constants.tsx
src/components/Avatar/types.ts

Adding an XS size to avatar to fix the first point of https://github.com/gatsby-inc/mansion/issues/5848
Here's the picture in XS, it's small 😝

Adding XS size to avatar

---

__tests__/__snapshots__/Storyshots.test.js.snap
src/components/Button/Button.tsx
src/components/Navigation/Navigation.js
src/components/Navigation/Navigation.stories.js
src/components/skeletons/BaseNavigation/BaseNavigationStyles.js
src/index.ts
src/theme/styles/navigation.js

This PR makes a few small tweaks:
- Aligns nav items to the right instead of left, to match latest designs
- Tweak dropdown positioning
- Adds `Nav.Spacer` to allow items to be pushed to the right
- Code cleanup (mostly carrying over some of the stuff I did in `BaseNavigationStyles`, in a previous PR, to `Navigation`)
Storybook GIF:
In-app Screenshots:

Update navigation component

---

src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/constants.tsx
src/components/Avatar/types.ts

Adding XXL size for avatar in 128x128 related to https://github.com/gatsby-inc/mansion/issues/5848#issuecomment-564758990
Here's a picture:

Adding Avatar XXL

---

package.json

This PR changes precommit hooks a little bit to make them more predictable and reliable. Previously, we would run both `lint` and `format` scripts even for files that were not staged for commit due to the way those scripts were configured. This is fixed with the following changes:
* `yarn lint` now supports passing a path (e.g. `yarn lint src/index.ts`)
* `yarn lint:all` has been added to lint every matching file from `src` directory
* `yarn format` now supports passing a path (e.g. `yarn lint src/components/Avatar/*.tsx`)
* `yarn format:all` has been added to format every matching file from `src` directory
These changes allow `lint-staged` to run lint and format scripts only for staged files. 
Once this PR is merged, I'd like us to explore an alternative approach to using ESLint + …

chore: add 'lint:all' and 'format:all' scripts

---

__tests__/__snapshots__/Storyshots.test.js.snap
src/components/Navigation/Navigation.stories.js
src/components/skeletons/BaseNavigation/BaseNavigation.js
src/components/skeletons/BaseNavigation/BaseNavigationStyles.js
src/theme/styles/navigation.js

Our navigation component needed two more tweaks:
- On mobile, the list was showing horizontally instead of vertically
- We needed to support a "split" navigation, with items on either side.
The former was a quick fix, two lines of CSS.
The latter was a bit more trouble, but I solved it by adding a new `secondaryItems` prop, wrapping both sides in a flex container, and shoving a spacer between them to force them to each end.
With secondaryItems:
with root children (unchanged):

Two navigation fixes

---

src/theme/breakpoints.ts

Turns out my implementation of `breakpoints` scale in #177 was incorrect — it was out of order and did not adhere to the exact spec from [ThemeUI docs](https://theme-ui.com/theming/#breakpoints).
This PR fixes that and adds a comment to explain the scale transformation.

fix: correctly transform breakpoints scale for ThemeUI

---

__tests__/__snapshots__/Storyshots.test.js.snap
src/components/Avatar/Avatar.helpers.tsx
src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/Avatar.tsx
src/components/Avatar/constants.tsx

Fixes #136 by using binary search to find the most fitting font size for an avatar fallback text. Inspired by and based on [textFit](https://github.com/STRML/textFit).

feat: fit fallback text to Avatar size

---

src/components/form-skeletons/components/FormFieldSkeleton.tsx
src/components/form-skeletons/components/InputFieldSkeleton.tsx
src/components/form-skeletons/stories/form.stories.tsx
src/components/form-skeletons/stories/storyUtils.ts
src/components/form/components/FormField.tsx
src/components/form/components/InputConnectedField.tsx
src/components/form/components/InputField.tsx
src/components/form/components/InputFieldBlock.tsx
src/components/form/index.ts
src/components/form/stories/form.FormField.stories.tsx
src/components/form/stories/form.InputField.stories.tsx
src/components/form/stories/form.WithFormik.stories.tsx

This PR is the first in a series of changes needed to get rid of static properties from our components to enable Webpack tree shaking. It only covers `InputFieldSkeleton`, `InputField` and `InputFieldBlock` components, as well as makes some updates in `FormFieldSkeleton` and `FormField` which are necessary for this work.
The changes can be generally described as follows:
* `FormFieldSkeleton` now exports its compound parts in addition to specifying them as static properties:
```javascript
export const FormFieldSkeletonLabel = props => {
/* ... */
}
FormFieldSkeleton.Label = FormFieldSkeletonLabel
```
This is done to avoid rewriting ALL of form skeletons and fields; we'll omit static properties once all of skeleton components rely on named exports. 
* `FormField` is changed in a similar …

fix: remove static properties from Input form fields

---

src/components/Toggle/ToggleCheckbox.tsx
src/components/Toggle/ToggleGutter.tsx
src/components/Toggle/ToggleSwitch.tsx

* Remove static properties from internal `ToggleGutter` component to allow tree shaking with Webpack
* Lift up the default label styles for `ToggleCheckbox` and `ToggleSwitch` for easier customization

fix: remove static properties from ToggleGutter, fix label styling

---

src/components/form-skeletons/components/InputFieldSkeleton.tsx
src/components/form-skeletons/components/TextAreaFieldSkeleton.tsx
src/components/form-skeletons/stories/form.stories.tsx
src/components/form/components/InputField.tsx
src/components/form/components/TextAreaConnectedField.tsx
src/components/form/components/TextAreaField.tsx
src/components/form/components/TextAreaFieldBlock.tsx
src/components/form/index.ts
src/components/form/stories/form.FormField.stories.tsx
src/components/form/stories/form.TextareaField.stories.tsx
src/components/form/stories/form.WithFormik.stories.tsx

In continuation of #213, here's a PR to replace static properties with named exports for `TextAreaField` and `TextAreaFieldSkeleton`.
It also fixes some minor type mismatches in `InputFieldSkeleton`.

fix: remove static properties from TextArea form fields

---

src/components/form-skeletons/components/SelectFieldSkeleton.tsx
src/components/form-skeletons/stories/form.stories.tsx
src/components/form/components/SelectConnectedField.tsx
src/components/form/components/SelectField.tsx
src/components/form/components/SelectFieldBlock.tsx
src/components/form/index.ts
src/components/form/stories/form.FormField.stories.tsx
src/components/form/stories/form.SelectField.stories.tsx
src/components/form/stories/form.WithFormik.stories.tsx

In continuation of #213, here's a PR to replace static properties with named exports for `SelectField` and `SelectFieldSkeleton`.

fix: remove static properties from Select form fields

---

src/components/SidebarNav/SidebarNav.tsx

So, apparently our `theme.fontWeights.bold` is not the same as `"bold"` for some of our fonts, it actually looks bolder, so I've updated `SidebarNav` to use `"bold"` for its "active" items. It should still give enough distinction to identify an active item in addition to the color usage.

fix: use 'bold' font weight for active SidebarNav link

---

src/components/skeletons/BaseNavigation/BaseNavigation.js

aria-expanded was "active" and "undefined".
It's now "true" or "false" on the burger icon :)

Fixing a11y issue on navbar

---

package.json
rollup.config.js

Adds a CommonJS bundle in addition to ESM one. This is done mostly to avoid Jest tests breaking due when node_modules are not being transpiled.

chore: add CommonJS bundle

---

src/components/BaseNavigation/BaseNavigation.tsx
src/components/Navigation/Navigation.js

Fixing a11y issue on the navbar where a div was spot in the middle of a ul.
Thanks to https://github.com/gatsby-inc/gatsby-interface/issues/239#issuecomment-603314292 🚀 🎉

Fixing navigation issue

---

.storybook/preview.js
.storybook/theming.tsx
__stories__/about/Intro.stories.mdx
__stories__/about/Usage.stories.mdx
package.json
src/components/CopyButton/__tests__/__snapshots__/CopyButton.test.tsx.snap
src/components/Toast/__tests__/__snapshots__/Toast.js.snap
yarn.lock

With this PR we should get Storybook Docs use our own components for text and headings.
A couple of notes:
*  `DocsCodeOrSourceMdx` is introduced because Storybook for some reason does not apply `fontCode` style to `<code>` tag in MDX 🤷‍♂ 
* Custom components for MDX are rendered with our `ThemeProvider`, otherwise they would receive their theme scales from Storybook

chore: fix dependencies to support Storybook Docs theming

---

README.md

We switched the live Storybook URL from from https://reverent-keller-9597e8.netlify.com/ to https://gatsby-interface.netlify.com/. This PR adjusts the link in the `README`.
Rewrote and reordered stuff a little along the way; preview here: https://github.com/gatsby-inc/gatsby-interface/blob/23dd1c16e0e9c2104f5034fc6a4ab9847dbbf6af/README.md

fix: adjust README to new Netlify URL

---

src/components/Navigation/Navigation.js
src/components/Navigation/Navigation.stories.js
src/theme/styles/navigation.js

Zeroes padding and margin of each `<li>` in `Navigation` so that navigation buttons are aligned even in cases when some normalizer is used together with this componentFor example, this is how Cloud nav would look on the current version without this fix:

CSS reset for Navigation list items

---

src/components/BaseNavigation/BaseNavigation.tsx
src/components/Navigation/Navigation.js
src/components/Navigation/Navigation.stories.js

In the Will It Build project, we have 1 link (API Playground) that needs to use an `<a>` tag rather than a `<Link>`, since the page is outside of the Gatsby app (links to `willit.build/api-playground`, but we're using Netlify rewrites to actually show a Graphiql playground)
I tried to follow the pattern established with @Elanhant for the `NavigationButton`; `BaseNavigation` has two separate primitives, but `Navigation` looks at the `linkTo` to determine which should be used.

Allow `Navigation` to link to external URLs

---

src/theme/theme.stories.tsx

Sppontaneously nudged @greglobinski great z-indices diagram a bit to show the token value:
- add constants `offset`, `labelWidth`
- change `maxSize` to `maxWidth`,  add and fix `maxHeight` (which was too big before, resulting in the diagram being positioned slightly off)
- adjust `colorsByToken` a little
- add a fixed `width` to the diagram container, which honors `labelWidth`, thus allowing to right-align the `zIndices` _value_ 🎉
Currrently:

chore: display theme.zIndices value

---

scripts/scaffold-component/story-template.ejs
src/components/Announcement/Announcement.stories.tsx
src/components/Badge/Badge.stories.tsx
src/components/BaseNavigation/BaseNavigation.stories.tsx
src/components/Combobox/Combobox.stories.tsx
src/components/ConcealedValue/ConcealedValue.stories.tsx
src/components/Heading/Heading.stories.tsx
src/components/Modal/Modal.stories.tsx
src/components/Modal/ModalCard.stories.tsx
src/components/Modal/ModalFullScreen.stories.tsx
src/components/Modal/ModalPanel.stories.tsx
src/components/Notification/Notification.stories.tsx
src/components/SidebarNav/SidebarNav.stories.tsx
src/components/StepIndicator/StepIndicator.stories.tsx
src/components/Toggle/ToggleCheckbox.stories.tsx
src/components/Toggle/ToggleSwitch.stories.tsx
src/components/Tooltip/Tooltip.stories.tsx
src/components/form/stories/InputField.stories.tsx
src/components/form/stories/InputFieldBlock.stories.tsx
src/components/form/stories/SelectField.stories.tsx
src/components/form/stories/SelectFieldBlock.stories.tsx
src/components/form/stories/TextAreaField.stories.tsx
src/components/form/stories/TextAreaFieldBlock.stories.tsx

We don't really need to perform visual regression testing for "Sandbox" stories since those usually look the same as their "Basic" counterparts. 
This PR excludes all of the existing "Sandbox" stories from Chromatic checks and updates the `.stories.tsx` template accordingly.

chore: exclude Sandbox stories from Chromatic

---

src/components/Notification/Notification.stories.tsx
src/utils/storybook/index.ts
src/utils/storybook/propsCombinationStory.tsx

Adds a new Storybook util, `sandboxWithPropVariations`, that allows to display a component with different values for a selected prop via Knobs add-on.
To use this util function, you'll have to update your "Sandbox" story. For example, if you had something like this:
```jsx
const VARIANTS: MyComponentVariant[] = ['foo', 'bar']
export const Sandbox = () => (
<MyComponent
children={text('children', 'Lorem ipsum')}
variant={radios('variant', radioKnobOptions(VARIANTS), 'foo')}
/>
)
```
then you'll need to change it to this:
```jsx
const VARIANTS: MyComponentVariant[] = ['foo', 'bar']
export const Sandbox = () => sandboxWithPropVariations(propVariations => (
<MyComponent
children={text('children', 'Lorem ipsum')}
variant={radios('variant', radioKnobOptions(VARIANTS), 'foo')} …
```

chore: add an util to list prop variations in a sandbox

---

.babelrc
package.json
src/components/Modal/StyledModal.stories.tsx
src/components/Modal/StyledPanel.stories.tsx
src/components/StepIndicator/StepIndicator.stories.tsx
src/components/StickyObserver/StickyObserver.stories.tsx
yarn.lock

This PR should make JSDoc comments visible to Storybook Docs, allowing to add component [descriptions](https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/docspage.md#description) and [props](https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/docspage.md#props); the latter is lacking a lot at the moment (e.g. union props are described just as "union" 🤷‍♂), but it's still better than nothing.

chore: setup docgen for Storybook Docs

---

src/components/form-skeletons/components/CheckboxGroupFieldSkeleton.tsx
src/components/form-skeletons/components/RadioButtonFieldSkeleton.tsx
src/components/form/components/CheckboxConnectedField.tsx
src/components/form/components/InputConnectedField.tsx
src/components/form/components/InputFieldBlock.tsx
src/components/form/components/RadioButtonField.tsx
src/components/form/components/RadioButtonFieldBlock.tsx
src/components/form/components/SelectConnectedField.tsx
src/components/form/components/TextAreaConnectedField.tsx
src/components/form/index.ts

* Adds a `RadioButtonFieldOptionItem` component that can be used for custom option render in `RadioButtonFieldBlock` or `RadioButtonConnectedField`
* Allow to pass most of `<input>` props in `options` array for `RadioButtonFieldBlock` or `RadioButtonConnectedField`.
* Allows to pass `ref` prop to `CheckboxConnectedField`, `InputConnectedField`, `SelectConnectedField` and `TextAreaFieldBlock` components. This can be used in cases such as setting focus on mount.
* Exposes `useConnectedField` hook

Form updates for radio button block and connected single input blocks

---

src/theme/index.ts
src/theme/tones.ts

Noticed today that we seem to have two places where the `TONE` scale is defined:
1. https://github.com/gatsby-inc/gatsby-interface/blob/e91f105c556752717ec5ded781c9efd64575832f/src/theme/index.ts#L34-L75
2. https://github.com/gatsby-inc/gatsby-interface/blob/e91f105c556752717ec5ded781c9efd64575832f/src/theme/tones.ts#L13-L54
The one in `theme/index` is the more recent one, with adjusted `WARNING` colors: Latter adjustments happened in
- #242 / https://github.com/gatsby-inc/gatsby-interface/pull/242/files#diff-42c090954509eda0d00c8ebb63467ec1
- #293 / https://github.com/gatsby-inc/gatsby-interface/pull/293/files#diff-42c090954509eda0d00c8ebb63467ec1
This PR consolidates the two definitions.  
(Let the TS lottery being … 😅🤞)

fix: SSOT for `tones`

---

src/components/Badge/Badge.helpers.tsx
src/components/PlanIndicator/PlanIndicator.tsx
src/theme/tones.ts

- chore: use `border` instead of `boxShadow` for `<Badge>`
- `minHeight` and `box-sizing: border-box` got our back
- let's stick to one strategy for displaying a border for now
- makes borders slightly more prominent
- chore: introduce `tone.lighter` and use it as `border` color for `<Badge>`
- tone.light is only used for Badge.STATUS and button.SECONDARY borders
- for button.SECONDARY, we want slightly darker borders
- nicely fills the gap between `superLight` and `light` (as opposed to `dark`, `darker`, `superDark`)

chore: Use `border` instead of `boxShadow` for badge; add `tone.lighter`

---

src/utils/storybook/StoryUtils.tsx

Actually like the `Chip` look-and-feel more, but this is about semantics ;) …

chore: Use Badge instead of Chip for `StoryUtils.Default`

---

src/theme/theme.stories.tsx

Borrowing heavily from https://github.com/uber/baseweb/blob/07befaffd7b5e61792adac44e66da70918f54487/documentation-site/components/theming/animations.js 🙏, this adds continuously animated examples for the theme's `transitions` scale.
https://deploy-preview-306--gatsby-interface.netlify.app/?path=/story/theme-scales--transitions
- show token value in story; fixes #303
- move `curve` examples down
- don't mix `curve` example `speed` with token, display it next to the headline instead
- increase default `curve` example speed to `1000ms` (was `500ms`)
- make `zIndices` example border calmer

chore: Show `transitions` token values, add auto-animated examples

---

src/components/CopyButton/__tests__/__snapshots__/CopyButton.test.tsx.snap
src/theme/styles/button.ts

- use `transition` tokens for transition durations
- make transitions snappier: change transition duration from `500ms` to `250ms`
Fixes #304

feat: Make `<Button>` transitions snappier, use theme tokens

---

src/index.ts

Addresses [`ch4851`](https://app.clubhouse.io/gatsbyjs/story/4851/hextorgba-helpers-should-be-exposed-by-gatsby-interface).

Expose hexToRGB and hexToRGBA helpers

---

src/components/Combobox/Combobox.stories.tsx
src/components/Combobox/Combobox.styles.tsx
src/components/Combobox/Combobox.tsx
src/components/Combobox/__tests__/Combobox.test.tsx
src/utils/maintenance/deprecationMessages.ts
src/utils/maintenance/warn.ts
src/utils/types.ts

* Allow clicks through the displayed selected value (when `selectedOptionLabel` is passed); otherwise users would not be able to reopen the popover by clicking into the input once they select an option.
* Require to explicitly pass `aria-labelledby` or `aria-label` to the `ComboboxList` component.  
* Display options popover in a portal by default

fix: various Combobox fixes

---

src/components/PlanIndicator/PlanIndicator.stories.tsx
src/components/PlanIndicator/PlanIndicator.tsx

We need to add the trialing / professional plan as a badge 
This badge doesn't have an icon and is in green

Adding Trialing (professional trial) as a plan

---

src/components/SidebarNav/SidebarNav.tsx

Saves a bit of horizontal space, and (subjectively ;)) feels better — before/after:

chore: Realign `SidebarNav` subitems to save horizontal space

---

src/components/SidebarNav/SidebarNav.stories.tsx
src/components/SidebarNav/SidebarNav.tsx
src/components/SidebarNav/index.ts

…and thus all variants of the component:
- Not used in Gatsby Cloud.
- `maxWidth: 8rem` that the `FULL` variant sets on `SidebarNavList` could be set on its parent `SidebarNav` via Emotion's `css` prop or `styled` (at `10rem`, taking `SidebarNav`s `padding-left` into account).
- Remove `Variants` story, knob in `Sandbox` story.
Fixes #326

chore: Remove `SidebarNav variant="FULL"`

---

package.json

Pinning the peer dependency version of Gatsby is leading to users complaining about mismatched peer deps now that `gatsby-interface` is installed with every `gatsby` install: https://github.com/gatsbyjs/gatsby/issues/24653
I might be missing the reasoning behind it, so feel free to suggest a better solution, but this PR adds a caret to the peer dep which will resolve this issue.

Unpin gatsby peer dependency

---

scripts/run-chromatic.js

This PR stops CI `is-green` check from failing if there were any visual regressions detected by Chromatic, as this doesn't make any sense when `UI Tests` and `UI review` checks are already required for merge.

chore: do not stop CI jobs on failed Chromatic test

---

src/components/PlanIndicator/PlanIndicator.tsx

The existing color contrast for the "Free" and "Professional Trial" variants of PlanIndicator don't have sufficient contrast. To remedy that, I've changed the text colors for both.
Note that the "Free" plan was only the darkest/highest contrast orange value available, which I why I switched to a red value. To me it still seems complementary. Thoughts, @fk ?

Color contrast tweaks for several PlanIndicator variants

---

src/components/form-skeletons/components/CheckboxFieldSkeleton.tsx
src/components/form-skeletons/components/CheckboxGroupFieldSkeleton.tsx
src/components/form-skeletons/components/FormFieldSkeleton.tsx
src/components/form-skeletons/components/FormGroupFieldSkeleton.tsx
src/components/form-skeletons/components/InputFieldSkeleton.tsx
src/components/form-skeletons/components/RadioButtonFieldSkeleton.tsx
src/components/form-skeletons/components/SelectFieldSkeleton.tsx
src/components/form-skeletons/components/TextAreaFieldSkeleton.tsx
src/components/form/components/CheckboxField.tsx
src/components/form/components/CheckboxGroupField.tsx
src/components/form/components/InputField.tsx
src/components/form/components/RadioButtonField.tsx
src/components/form/components/SelectField.tsx
src/components/form/components/TextAreaField.tsx
src/utils/maintenance/deprecationMessages.ts

Now when #340 is merged, we can start deprecating `*FieldSkeleton` and `*Field` components (e.g. `InputFieldSkeleton` and `InputField`) — they can be replaced with the new hooks and styled form elements.
By the way, the only deprecated components used in Cloud codebase are `RadioButtonFieldSkeleton` (which gave us those a11y warnings about not using `<fieldset>`), `InputField` (which I have already replaced in an outstanding PR) and `RadioButtonField`. Their total usage number is about 10, and they shouldn't be to difficult to replace with the `*FieldBlock` counterparts or `useAriaFormField`/`useAriaFormGroupField` hooks.

chore: add deprecation notice to *FieldSkeleton and *Field components

---

src/components/Card/Card.stories.tsx
src/components/Card/Card.tsx
src/components/Card/index.ts
src/theme/index.ts
src/utils/storybook/storyData.ts

A prototype for `Card` component. 
The biggest shift compared to how we currently implement cards is moving the responsibility for spacing from the "root" card component to a `CardSection` subcomponent. `CardComponent` can be used to apply default card space around other elements with an option to disable space on any side via passing `applyPaddingTop={false}` (or/and `applyPaddingBottom`, `applyPaddingLeft`, `applyPaddingRight`).
Available components:
* `Card` — root component, takes care of background color and border
* `CardSection`
* `CardHeader`
* `CardFooter`
* `CardDivider`

feat(Card): initial prototype for Card component

---

__tests__/__snapshots__/icons.test.js.snap
src/components/ThemeProvider/ThemeProvider.stories.tsx
src/components/icons/BitbucketIcon.tsx
src/components/icons/EllipsisIcon.tsx
src/components/icons/InProgressIcon.tsx
src/components/icons/SkullIcon.tsx
src/components/icons/icons.stories.tsx

Fixes some a11y issues detected by axe in icons and `ThemeProvider` stories, also rewrites stories for the latter in CSF format.

chore: fix a11y issues in some stories

---

src/components/AnchorButton/AnchorButton.tsx
src/components/Button/Button.stories.tsx
src/components/Button/Button.tsx
src/components/LinkButton/LinkButton.tsx
src/theme/styles/button.ts

Adds a new prop, `width`, to `Button`, `LinkButton` and `AnchorButton` to support "Full width" variant defined in the design. 
Allowed values are:
* `AUTO` — default value, button's width fits its content
* `FIT_CONTAINER` — makes the button take all available width
**NOTE:** I chose `FIT_CONTAINER` instead of `FULL_WIDTH` as IMO it is more appropriate for the actual behaviour; however, I am not too attached to it and can change if needed.

feat(Button): support new prop, width

---

src/components/EmptyState/EmptyState.tsx

Fixes TypeScript error when trying to use `EmptyStatePrimaryAction` as a Gatsby Link by passing `to` prop.

fix(EmptyState): fixes props type for EmptyStatePrimaryAction

---

src/components/Modal/ModalPanel.tsx

Changes default size for `ModalPanel` to 432px or 100% if screen width is less than that value. I don't think we've been using `maxWidth` anywhere in Cloud, but to be safe I've decided to keep it for now and add a deprecation message.
I have not changed the purple color of the overlay since its shared between normal modals and panels, will take care of that in a different PR later.
Preview available in [Chromatic](https://5d4c6885a869c600201d3c8b-pwghngfmjx.chromatic.com/?path=/story/modal-styledpanel--usage-example).

feat(Modal): changes default size for ModalPanel

---

src/components/Text/Text.helpers.ts

The Text component hardcodes the use of the "system" font stack. This unfortunately means that to globally use a different font family we have to override it in the theme like so:
```JS
const theme = {
...baseTheme,
fonts: {
...baseTheme.fonts,
system: '...other fonts...'
}
}
```
But then manually using `fontFamily: 'system'` no longer shows system fonts. That is really confusing! :confused:
Instead, this PR changes the Text component to use the "body" font stack, which is aliased to "system" by default anyway, so no behavior changes. We can then adjust that font stack without anything being confusing! :tada:
```JS
const theme = {
...baseTheme,
fonts: {
...baseTheme.fonts,
body: '...other fonts...'
}
}
```

Use "body" font family for <Text />

---

__tests__/__snapshots__/icons.test.js.snap
src/components/icons/InProgressIcon.tsx
src/components/icons/icons.stories.tsx

Makes `InProgressIcon` animated similar to what we do in Gatsby Cloud for build status icon. 
Like most other icons, this one can be colored by applying some `color` CSS, e.g.
```typescript
import { InProgressIcon, ThemeCss } from "gatsby-interface"
const purpleIconCss: ThemeCss = theme => ({
color: theme.colors.gatsby,
})
function PurpleInProgressIcon() {
return <InProgressIcon css={purpleIconCss} />
}
```
https://5f2b05a6b9c58d00084532bb--gatsby-interface.netlify.app/?path=/story/icons-single-icons--inprogressicon

Animated InProgressIcon

---

src/components/IconButton/IconButton.tsx
src/theme/styles/button.ts

Makes button sizes the same as the ones in Figma.
**IMPORTANT** ~needs review for the changes in other components (see Chromatic CI checks) and potentially trying this out in Gatsby Cloud before merging.~ Seems to be OK, with env vars form being the only thing in Gatsby Cloud that needs updating.
https://deploy-preview-375--gatsby-interface.netlify.app/?path=/story/button-anchorbutton-linkbutton--sizes

fix(buttons): Adjust button sizes to match the design

---

docs/icons.md

This is a very short and basic doc on using and adding icons to gatsby-interface.

Basic docs on using and adding icons

---

src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/AvatarsGroup.tsx

This should fix the overlap issue happening in Gatsby Cloud (https://github.com/gatsbyjs/gatsby/issues/26739). The reason for that issue is that we are not resetting z-index stacking context in `AvatarGroup` which results in having to adjust dropdown menu's `z-index`.
I have also updated related stories in Storybook to follow Component Story Format.

fix(Avatar): start a new z-index stack for AvatarsGroup

---

src/theme/utils/TextShowCase.tsx

Fixes this display for raw values in "Font SIzes" story:
Fixed:

chore: fix tiny ui issue with font sizes story [ci skip]

---

src/components/BuildLogs/BuildLogsList.stories.tsx
src/components/BuildLogs/BuildLogsList.tsx
src/components/BuildLogs/BuildStandardLogEntry.tsx
src/components/BuildLogs/FormattedLogMessage.tsx
src/components/BuildLogs/FormattedMessage.tsx
src/components/BuildLogs/__tests__/FormattedMessage.spec.tsx
src/components/BuildLogs/types.ts

Show more information on errors when it's available:

feat(BuildLogs): Display docsUrl and errorUrl for errors

---

.circleci/config.yml
.github/workflows/prerelease.yml
scripts/prerelease-branch.js
src/components/Portal/Portal.stories.tsx
src/components/Toast/Toast.stories.tsx

Replace automatic branch pre-release with a manual GitHub Action (you can find it in [Actions](https://github.com/gatsby-inc/gatsby-interface/actions)). 
To trigger a branch pre-release:
* Go to [Actions](https://github.com/gatsby-inc/gatsby-interface/actions)
* Pick "Pre-release" in the left sidebar ("Workflows"):
* Click "Run workflow" button to the right, and select a branch. Click "Run workflow" button below the branch dropdown:
**NOTE:** pre-releases for `main` branch are not supported at the moment (similar to the old CircleCI job).

Setup manual pre-release action

---

src/components/Card/Card.tsx
src/components/Combobox/Combobox.tsx
src/components/DropdownMenu/DropdownMenu.stories.tsx
src/components/DropdownMenu/DropdownMenu.tsx

Fixes several TypeScript errors that might occur when using Gatsby Interface:
* Using a React element as `title` for `CardHeader` would result in an error, since the prop type from `CardHeaderProps` conflicts with the type for `title` attribute on `<div>`/`<header>` elements. 
* `ComboboxPopover` had incorrect type specified for its `ref` — it was `HTMLInputElement` instead of `HTMLDivElement`.
* `DropdownMenuLink` would not accept any `as` prop other than `"a"`; I had to use ReachUI's utility helper `forwardRefWithAs` in order to fix this.

fix: various TypeScript fixes

---

package.json
src/components/DropdownMenu/DropdownMenu.stories.tsx
src/components/DropdownMenu/DropdownMenu.styles.tsx
src/components/DropdownMenu/DropdownMenu.tsx
src/components/DropdownMenu/__tests__/DropdownMenu.test.tsx
yarn.lock

While using CSS keyframes to animate an opened dropdown menu is the simplest solution, it breaks our Jest tests that check for dropdown menu items to be visible (using Testing Library matchers). This is due to Jest environment being unable to detect style changes coming from keyframes. 
To fix this and allow us to test for menu visibility again, I have switched to [`useSpring`](https://www.react-spring.io/docs/hooks/use-spring) from React Spring. It explicitly injects styles into DOM which allows to actually check whether the animated menu is visible. 
**NOTE:** I have initially tried to animate with `useTranisition`, but it resulted in some unpleasant bugs when the user quickly reopens the menu after closing (e.g. when using keyboard).
@fk be my guest to play with the spring …

fix: replace keyframes with spring animation for DropdownMenu

---

src/components/Toast/Toast.tsx

ReachUI's `Alert` does not support access to React Context from inside the component to outer providers, which results in uncaught errors when using Emotion for elements like "Close" button. 
This PR wraps each `Alert`'s children in `ThemeProvider` to provide the necessary theme context.

fix: fix Toast throwing an error on render

---

src/components/BuildLogs/BuildLogsList.stories.tsx
src/components/BuildLogs/FormattedMessage.tsx
src/components/BuildLogs/__tests__/FormattedMessage.spec.tsx

The generated markdown was invalid when there were multiple code blocks.
Before
After

fix(BuildLogs): Handle multiple code blocks

---

package.json
src/components/Modal/StyledPanel.stories.tsx
src/components/Modal/StyledPanel.tsx
src/components/StickyObserver/StickyObserver.tsx

Adds a shortcut for rendering panels — `StyledPanelBoilerplate` — which can be used in the new Member Management portal, and I am also trying it out for the CMS integration forms:
<details>
<summary>Spoiler alert!</summary>
</details>

feat(Modal): add StyledPanelBoilerplate component

---

src/components/form/components/CheckboxConnectedField.tsx
src/components/form/hooks/useConnectedField.ts

`CheckboxConnectedField` currently does not work properly if its initial value is `true` — it does not inject the `checked` prop to the checkbox under the hood, essentially resulting in the latter behaving like an uncontrolled input. 
This PR extends `useConnectedField` hook signature to match the one from Formik's `useField` for better checkbox support., allowing to pass a field configuration object instead of the field name.

fix(forms): fix CheckboxConnectedField not properly applying 'checked' state

---

src/components/form/hooks/useConnectedField.ts

The changes to `useConnectedField` from #411 resulted in an obscure bug with `RadioButtonConnectedField` — now the selected radio option did not have its "checked" state applied properly. It was caused by this line:
```typescript
const connectedProps: ConnectedFieldProps<TValue> = {
checked: field.checked,
}
```
When we defined `checked` prop like this, it will _always_ be present in the object, even if it's `undefined`. This, in turn, affects props override logic. In `RadioButtonFieldBlock` (wrapped by `RadioButtonConnectedField`) we have this element:
```jsx
<StyledRadioButton
value={value}
// Support uncontrolled field
checked={
fieldValue === undefined ? undefined : fieldValue === value
}
{...getOptionControlProps(value)}
{...rest}
{...restOption}
/>
```
The`...rest` in that element …

fix(form): desctructure Formik's field props instead of copying them

---

src/components/RawLogs/RawLogs.tsx

Clubhouse: https://app.clubhouse.io/gatsbyjs/story/16929/show-line-breaks-in-the-raw-logs-ui
Current `RawLogs` ignore  line breaks in messages `\n`. This change should improve readability.
.
Current shape: `success` messages are combined in single rows if they come from the same timestamp
With this PR: every `success`, `info` and `error` starts from the new line as it is in `cli`
Bigger preview:
Mobile styles:

Show line breaks in RawLogs

---

src/components/RawLogs/RawLogs.tsx

Check existence of `message` before start formatting.  The PR will prevent future Sentry errors like this https://sentry.io/organizations/gatsby-inc-9z/issues/1973075081/?project=1405194&referrer=slack

Sanity check in formatMessage at RawLogs

---

src/components/BuildLogs/BuildLogsList.stories.tsx
src/components/BuildLogs/FormattedMessage.tsx
src/components/BuildLogs/__tests__/FormattedMessage.spec.tsx

Before the code block ends before the stack trace:
After:

fix(BuildLogs): Format gaphql errors with stacktraces

---

src/components/SidebarNav/SidebarNav.stories.tsx
src/components/SidebarNav/SidebarNav.tsx

To fix issues with inner page linking (https://app.clubhouse.io/gatsbyjs/story/16993/the-scroll-to-section-isn-t-working-in-the-site-settings-side-bar) we have to use `a` tag instead of Gatsby `Link`  more context here https://gatsbyjs.slack.com/archives/CGJ457QTT/p1603890513003300 
Related PR https://github.com/gatsby-inc/mansion/pull/9916

SidebarNav fix for inner page links

---

package.json
src/theme/utils/ColorPaletteModal.tsx
src/theme/utils/ColorsTable.tsx
yarn.lock

As the title says — this PR brings back the palette modal for each of our main colors. This modal can be opened by clicking on the color name in Colors story.
It will definitely need some polishing, but it should do its job for now 🙂

chore: bring back color palette modal

---

src/components/icons/HostingIcon.tsx

Replace `stroke-width` with `strokeWidth` to stop React complains in `console`

fix: HostingIcon svg property

---

src/components/BaseText/BaseText.tsx
src/components/Text/Text.tsx

* Allows to use `div` in `Text`'s and `BaseText`'s `as` prop.
* `Text` now accepts `noMarginTop` and `noMarginBottom` props, which allow to reset browser defaults for the corresponding CSS properties.

feat(Text): support as='div' and margin reset props

---

src/components/form/components/styled-primitives/StyledTextArea.tsx
src/components/form/stories/connectedFields.stories.tsx

Currently we have to do some terrible things if we want to use `rows` attribute for text areas:
```jsx
<TextAreaFieldBlock
rows={10}
css={{ textarea: { height: `auto` } }}
/>
```
This was due to `StyledTextArea` inheriting styled input styles which have an explicitly set height. This PR fixes this oversight by setting `height: auto` for styled text areas.

fix(form): set StyledTextArea's height to 'auto' so that 'rows' attribute works

---

src/components/DropdownMenu/DropdownMenu.stories.tsx
src/components/DropdownMenu/DropdownMenu.styles.tsx
src/components/DropdownMenu/DropdownMenu.tsx

`DropdownMenuLink` and `DropdownMenuItem` now support two new props: `tone` and `Icon`. If this is approved and shipped, we can use those props to replace our `DropdownMenuActionLabel` component in Cloud.

feat(DropdownMenu): add support for 'tone' and 'Icon' props

---

src/components/DropdownMenu/DropdownMenu.stories.tsx
src/components/DropdownMenu/DropdownMenu.styles.tsx
src/components/DropdownMenu/DropdownMenu.tsx

In #429 I have added support for `Icon` to dropdown items, but the vertical alignment was off. I have updated it based on [this article](https://blog.prototypr.io/align-svg-icons-to-text-and-say-goodbye-to-font-icons-d44b3d7b26b4) and also fixed sizing issues with icons from Gatsby Interface.
I have also made the icons more vibrant by bumping their default shades of grey and red a bit.

fix(DropdownMenu): fix icon's vertical alignment and make it more opaque

---

src/components/NumberBadge/NumberBadge.stories.tsx
src/components/NumberBadge/NumberBadge.tsx

To use `NuberBadge` as component presenting the new updated Lighthouse scores we need to extend its functinality
- add `SUCCESS` tone
- add `withBorder` prop

Add SUCCESS tone and withBorder prop to NumberBadge

---

package.json
src/components/BuildLogs/BuildLogsList.stories.tsx
src/components/BuildLogs/FormattedMessage.tsx
src/components/BuildLogs/__tests__/FormattedMessage.spec.tsx

CB: https://app.clubhouse.io/gatsbyjs/story/23024/structured-logs-formatter-interferes-with-error-message
Because we are using `Markdown` to format structured log messages. When the message contains something like 
```
Can't resolve '../lerna_node_version.json' in '/usr/src/app/www/lerna_version_node/src/pages'
```
the underscores inside the path strings are transformed to `<em>` tags as it's expected for markdown transformation so that results with such a view for a user.
The PR prevents this by escaping `_` char if they are a part of a single quoted string.

[fix] Preserve changing '_' to <em> in structured log error message

---

src/components/Notification/Notification.helpers.ts

There is no need for `SECONDARY` and `SOLID` `Notification` to have such wide paddings. 
Let's unify the padding with the `PRIMARY` variant. 
This will let reproduce design for the Hosting Features banners. 
Now the banner looks like below. 
with the changes will look like here
Take a look at the Design Doc point 2. 
https://www.figma.com/file/95HMgM1GfqL86C0Ff33hnr/Hosting?node-id=2622%3A733

Unify paddings for all Notification variants

---

src/components/ProgressBar/ProgressBar.stories.tsx
src/components/ProgressBar/ProgressBar.tsx

Add second optional value to render in `ProgressBar`, need to present `site` scoped hosting usage & limits at Cloud.

ProgressBar extension - second value 

---

src/components/BuildLogs/FormattedMessage.tsx
src/components/BuildLogs/__tests__/FormattedMessage.spec.tsx

CH: This will fix the issue [File paths being interpreted as markdown](https://app.clubhouse.io/gatsbyjs/story/24424/file-paths-being-interpreted-as-markdown)

Add quoted paths to transformation to code block

---

src/components/BuildLogs/BuildLogsList.stories.tsx
src/components/BuildLogs/BuildStandardLogEntry.tsx
src/components/BuildLogs/types.ts

- CH: [Structured Logs/Raw logs Problems](https://app.clubhouse.io/gatsbyjs/story/31683/structured-logs-raw-logs-problems)
- update `displayMessage` construction at `BuildStandardLogEntry.tsx` to show `message` body also when `context.stageLabel` is defined. 
before: 
after:

Update displayMessage construction at BuildStandardLogEntry
