gatsby-inc/gatsby-interface

package.json
src/components/Tabs/BaseTab.js
src/components/Tabs/NumberedTab.js
src/components/Tabs/Tab.js

Add additional styles, all good in .com now

Fix tab styling

---

__stories__/StepIndicator.stories.js
src/components/StepsIndicator/StepsIndicator.js
src/components/StepsIndicator/index.js
src/index.js

- Add collapsible (ready)
- Add expanded (in progress, almost complete)

Add steps bar

---

package.json
src/components/StepsIndicator/StepsIndicator.js
yarn.lock

I've also updated the package to `0.0.26`

Fix css prop

---

.storybook/config.js
README.md
package.json
yarn.lock

Install chromatic 
I've updated the README on how to run it 
This tool is super cool 🎉

Install chromatic

---

src/components/Radio/Radio.js
src/components/Radio/Radio.stories.js

Fixes "emphasized" radio pushing its siblings when it is selected.

fix emphasized radio jumping when selected

---

src/components/FileUpload/FileUpload.js
src/components/FileUpload/FileUpload.stories.js
src/components/core/IntegrationRow/IntegrationRow.js

Fixing dev bugs so we can merge `dev` to `master`

Fix dev bugs

---

package.json
src/components/core/PricingCard/PricingCard.js
src/components/core/PricingCard/PricingCard.stories.js
src/index.ts
src/theme/fontWeights.js

Needed for https://github.com/gatsby-inc/mansion/pull/5105

Pricing card update [WIP]

---

src/index.ts

Quick fix for a forgotten export!

Export navigation

---

src/components/Navigation/Navigation.js
src/components/Navigation/Navigation.stories.js
src/components/skeletons/BaseNavigation/BaseNavigation.js

Following up from #210, this PR allows us to put external links inside Navigation.Button.

Support external links inside Navigation.Button

---

src/components/skeletons/BaseNavigation/BaseNavigation.js

Adding aria-label on Navigation burger

Adding aria-label on Navigation burger

---

src/components/ThemeProvider/ThemeProvider.stories.tsx
src/components/ThemeProvider/ThemeProvider.tsx

Allow to override theme values: https://github.com/gatsby-inc/gatsby-interface/issues/208

Allow theme provider to receive a theme property

---

.storybook/presets.js
.storybook/webpack.config.js
src/components/Avatar/AvatarsGroup.tsx
src/components/Chip/Chip.tsx
src/components/CopyButton/CopyButton.tsx
src/components/DecorativeDots/Dot.tsx
src/components/FileUpload/FileUpload.stories.js
src/components/Link/Link.tsx
src/components/Modal/Modal.tsx
src/components/Modal/ModalPanel.ts
src/components/Portal/index.ts
src/components/ThemeProvider/index.ts
src/components/Toast/MessageWithLink.tsx
src/components/Toast/Toast.tsx
src/components/Toast/ToastContext.tsx
src/components/Toast/ToastProvider.tsx
src/components/Toast/__tests__/Toast.js
src/components/Toast/__tests__/__snapshots__/Toast.js.snap
src/components/Toast/hooks.tsx
src/components/icons/types.tsx
src/theme/colors.ts
src/theme/tones.ts
src/theme/types.ts
src/utils/storybook/index.d.ts

Stumbled upon #185, and was in the mood to give that a shot.
LMK how far off I am, and if it's OK to jump on things like this?! 😰🙏

chore: run lint and format scripts

---

__stories__/Radio.stories.js
src/components/Badge/Badge.tsx
src/components/Card/CardTitle.js
src/components/SettingsBlock/SettingsBlock.js
src/components/Tabs/Tab.js
src/theme/styles/heading.js
src/theme/styles/navigation.js
src/theme/styles/text.js

Stops builds from failing because of `fonts.header`

chore: fix build script

---

src/components/Notification/Notification.tsx

Removing the console log from here 😅

Removing the logs for interface

---

src/theme/theme.stories.tsx

chore: show `theme.scale` pixel values

---

src/components/Modal/Modal.stories.tsx
src/components/Modal/ModalCard.stories.tsx
src/components/Modal/ModalFullScreen.stories.tsx
src/components/Modal/ModalPanel.stories.tsx
src/components/Modal/StyledModal.stories.tsx
src/components/Modal/StyledPanel.stories.tsx
src/components/form/stories/InputField.stories.tsx
src/components/form/stories/InputFieldBlock.stories.tsx
src/components/form/stories/SelectField.stories.tsx
src/components/form/stories/SelectFieldBlock.stories.tsx
src/components/form/stories/TextAreaField.stories.tsx
src/components/form/stories/TextAreaFieldBlock.stories.tsx
src/components/icons/icons.stories.tsx

Gathers form, icon and modal stories under top level groups:

chore: group some of the stories

---

src/components/form/components/CheckboxField.tsx
src/components/form/components/CheckboxGroupField.tsx
src/components/form/components/RadioButtonField.tsx
src/components/form/stories/CheckboxFieldBlock.stories.tsx
src/components/form/stories/CheckboxGroupFieldBlock.stories.tsx
src/components/form/stories/RadioButtonFieldBlock.stories.tsx

We were missing styles for disabled radio buttons and checkboxes, this PR aims to fix it.

fix: add missing styles for disabled radio buttons and checkboxes

---

CODE_OF_CONDUCT.md
README.md

- add [`CODE_OF_CONDUCT.md`](https://github.com/gatsbyjs/gatsby/blob/874088c3a7e58f74b4538d95d77069c1c1cb9267/CODE_OF_CONDUCT.md) from https://github.com/gatsbyjs/gatsby
- add a section "Code of Conduct" to the main `README`, following https://github.com/gatsbyjs/gatsby#-code-of-conduct
Fixes #317

fix: Add `CODE_OF_CONDUCT.md`, add section to README

---

src/components/Avatar/Avatar.stories.tsx
src/components/Badge/Badge.stories.tsx
src/components/Breadcrumb/Breadcrumb.stories.tsx
src/components/Button/Button.stories.tsx
src/components/DropdownMenu/DropdownMenu.stories.tsx
src/components/Modal/StyledModal.stories.tsx
src/components/Notification/Notification.stories.tsx
src/components/ProgressBar/ProgressBar.stories.tsx
src/components/Toast/Toast.stories.tsx
src/components/Toggle/ToggleSwitch.stories.tsx
src/components/Tooltip/Tooltip.stories.tsx
src/components/icons/icons.stories.tsx

Not for all, but for a subset of the available components … it's just a start, anyway! ;-)

feat: Add rudimentary `componentSubtitle`s

---

.storybook/preview.js
src/utils/storybook/StoryUtils.tsx

fix: addon-docs content not fully displaying

---

src/components/NumberBadge/NumberBadge.stories.tsx
src/components/NumberBadge/NumberBadge.tsx
src/components/NumberBadge/index.ts
src/index.ts
src/typings.d.ts
src/utils/storybook/components.tsx

Adds a new tiny `NumberBadge` component.

feat: NumberBadge component

---

package.json

fix: unpin gatsby, react and react-dom dependencies

---

.circleci/config.yml
scripts/prerelease-branch.js
scripts/run-chromatic.js

Update different tasks and configs to reflect the renaming of "master" to "main"

Change master to main

---

src/components/DropdownMenu/DropdownMenu.stories.tsx
src/components/DropdownMenu/DropdownMenu.styles.tsx
src/components/DropdownMenu/DropdownMenu.tsx

A couple of fixes for `DropdownMenuLink`:
* Make it forward refs to fix an error from ReachUI
* Apply the same styles as the ones for `DropdownMenuItem`

fix(DropdownMenu): style DropdownMenuLink and make it forward refs

---

src/components/BuildLogs/types.ts

Updates the Location type for BuildLogs to match what our GraphQL API.

fix(BuildLogs): Updates location types to match graphql

---

src/theme/utils/ColorsTable.tsx

…instead of serif —  
now/this:

chore(www): sans-serif for `ColorsTable`

---

src/theme/themeZIndices.stories.mdx

fix(docs): "Z-Indices" docs (Markdown) story title

---

package.json

chore: upgrade peer deps

---

src/components/RawLogs/RawLogs.tsx

Similar to https://github.com/gatsby-inc/mansion/pull/11974

[fix] turn off ligatures on raw logs font

---

src/components/EmptyState/EmptyState.tsx

[Update EmptyState component] (https://app.clubhouse.io/gatsbyjs/story/32863/update-emptystate-component)

  Update EmptyState component
